<div class="footer_">
  <div class="header" ><img src="images/logo2.png" alt="Swin-fi Logo"></div>
		<table>
			<tr><th> JOBS</th><th>INTRO</th><th>SOCIAL</th></tr>
			<tr><td><a href="apply.html">APPLY NOW</a></td><td><a href="enhancements2.html">CONTACT</a></td><td><a href="https://www.instagram.com/">INSTAGRAM</a></td></tr>
			<tr><td><a href="jobs.html">LEARN MORE</a></td><td><a href="about.html">ABOUT</a></td><td><a href="https://twitter.com/">TWITTER</a></td></tr>

			<tr><td></td><td><a href="enhancements.html">NEWS</a></td><td><a href="https://facebook.com/">FACEBOOK</a></td></tr>
		</table>
       <div class="emails_sec">
       	<h1><label for="email1"> GET EMAIL UPDATES</label></h1><br>
       	<input type="email"  id="email1" placeholder="Enter Email Address">
       	<input type="submit" value="Subscribe">
       </div>
	
	<hr>
	
</div>