<!--Header and Nav -->

<div class="header" ><img src="images/logo2.png" alt="Swin-fi Logo"></div>
<div class="nav"> 	
	<div class="menu">
	                  <span id="icon"> &#9831;</span>
	<div class="hello">
	<a href="index.html">Home</a>
	<a href="jobs.html">Learn More</a>
	<a href="apply.html">Apply Now</a>
	<a href="about.html">About Us</a>
	<a href="enhancements2.html">Contact Us</a>
	<a href="enhancements.html">News</a>


</div>

</div> </div>
 <a href="jobs.html" class="button"> Learn More &#8594;</a>
